version: "3.9"

services:
  node_db:
    container_name: node_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data
  farm:
    container_name: farm
    image: farm
    restart: always
    depends_on:
      - node_db
    build: .
    ports:
      - "5000:5000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=francesco
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  node_db_data: {}
#version: '3'
#services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: yourdbname
#      POSTGRES_USER: yourusername
#      POSTGRES_PASSWORD: yourpassword
#  app:
#    build: .
#    command: npm start
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - '3000:3000'
#    depends_on:
#      - db