version: "3.9"

services:
  db:
    container_name: "${POSTGRES_HOST}"
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - node_db_data:/var/lib/postgresql/data
  farm:
    container_name: farm
    image: farm
    restart: always
    depends_on:
      - db
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  node_db_data: {}
#version: '3'
#services:
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: yourdbname
#      POSTGRES_USER: yourusername
#      POSTGRES_PASSWORD: yourpassword
#  app:
#    build: .
#    command: npm start
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - '3000:3000'
#    depends_on:
#      - db